swiftlint_version: 0.48.0

opt_in_rules:
 - accessibility_label_for_image
 - anonymous_argument_in_multiline_closure
 - anyobject_protocol
 - array_init
 - attributes
 - balanced_xctest_lifecycle
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 - comment_spacing
 - conditional_returns_on_newline
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_first_not_nil
 - contains_over_range_nil_comparison
 - convenience_type
 - discarded_notification_center_observer
 - discouraged_assert
 - discouraged_none_name
 - discouraged_optional_boolean
 - discouraged_optional_collection
 - empty_collection_literal
 - empty_count
 - empty_string
 - empty_xctest_method
 - enum_case_associated_values_count
 - fallthrough
 - fatal_error_message
 - file_header
 - first_where
 - flatmap_over_map_reduce
 - force_unwrapping
 - ibinspectable_in_extension
 - identical_operands
 - implicit_return
 - implicitly_unwrapped_optional
 - inclusive_language
 - indentation_width
 - joined_default_parameter
 - last_where
 - legacy_multiple
 - legacy_random
 - literal_expression_end_indentation
 - lower_acl_than_parent
 - modifier_order
 - multiline_arguments
 - multiline_arguments_brackets
 - multiline_function_chains
 - multiline_literal_brackets
 - multiline_parameters
 - multiline_parameters_brackets
 - nslocalizedstring_key
 - nslocalizedstring_require_bundle
 - number_separator
 - operator_usage_whitespace
 - optional_enum_case_matching
 - overridden_super_call
 - override_in_extension
 - prefer_self_in_static_references
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - prefixed_toplevel_constant
 - private_action
 - private_outlet
 - private_subject
 - prohibited_super_call
 - raw_value_for_camel_cased_codable_enum
 - reduce_into
 - redundant_nil_coalescing
 - required_enum_case
 - return_value_from_void_function
 - single_test_class
 - sorted_first_last
 - sorted_imports
 - static_operator
 - strong_iboutlet
 - switch_case_on_newline
 - test_case_accessibility
 - toggle_bool
 - trailing_closure
 - unavailable_function
 - unneeded_parentheses_in_closure_argument
 - unowned_variable_capture
 - unused_closure_parameter
 - vertical_parameter_alignment_on_call
 - vertical_whitespace_closing_braces
 - vertical_whitespace_opening_braces
 - void_function_in_ternary
 - weak_delegate
 - xct_specific_matcher
 - yoda_condition

excluded:
  - Sources/TestUtils/Fixtures

# Rules customization
conditional_returns_on_newline:
  if_only: true

deployment_target:
  iOS_deployment_target: 1.0
  macOS_deployment_target: 10.0
  tvOS_deployment_target: 1.0
  watchOS_deployment_target: 1.0

file_header:
  required_pattern: |
                    \/\/(
                    \/\/ (SwiftGen(Kit)?|.* UnitTests)
                    \/\/ Copyright © 2022 SwiftGen
                    \/\/ MIT Licence
                    \/\/| Generated using SwiftGen — https:\/\/github.com\/SwiftGen\/SwiftGen)

indentation_width:
  indentation_width: 2

line_length:
  warning: 120
  error: 200

nesting:
  type_level:
    warning: 2
